name:                 BootstrapValidator
pygments:             false
relative_permalinks:  false

markdown:             redcarpet
destination:          _gh_pages
exclude:              ['node_modules', '*.less']
url:                  http://bootstrapvalidator.com/

# Custom variables
# not defined by Jekyll
current_version:      0.4.0
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/gh-pages
ga_code:              UA-44786951-2