name:                 BootstrapValidator
pygments:             false
relative_permalinks:  false

markdown:             redcarpet
destination:          _gh_pages
exclude:              ['node_modules', '*.less']
url:                  http://bootstrapvalidator.com/
#paginate:             5
permalink:            /news/:year/:month/:day/:title/
timezone:             Asia/Ho_Chi_Minh

# Custom variables
# not defined by Jekyll
current_version:      0.4.5
released_date:        2014-05-15
github_watchers:      535
github_forks:         213
github_downloads:     30540
twitter_followers:    95
download:
  dist:               https://github.com/nghuuphuoc/bootstrapvalidator/releases/download/v0.4.5/bootstrapvalidator-dist-0.4.5.zip
  tag:                https://github.com/nghuuphuoc/bootstrapvalidator/archive/v0.4.5.zip
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/gh-pages
ga_code:              UA-44786951-2
jquery_plugin_url:    http://plugins.jquery.com/bootstrapValidator
disqus:               bootstrapvalidator