name:         BootstrapValidator
markdown:     redcarpet
pygments:     true
highlighter:  pygments

destination:  _gh_pages
exclude:      ['node_modules']

redcarpet:
  extensions:     ['tables']
  with_toc_data:  1
