name:                 BootstrapValidator
pygments:             false
relative_permalinks:  false

markdown:             redcarpet
destination:          _gh_pages
exclude:              ['node_modules', '*.less']
url:                  http://bootstrapvalidator.com/

# Custom variables
# not defined by Jekyll
current_version:      0.4.4
download:
  dist:               https://github.com/nghuuphuoc/bootstrapvalidator/releases/download/v0.4.4/bootstrapvalidator-dist-0.4.4.zip
  tag:                https://github.com/nghuuphuoc/bootstrapvalidator/archive/v0.4.4.zip
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/gh-pages
ga_code:              UA-44786951-2
jquery_plugin_url:    http://plugins.jquery.com/bootstrapValidator