name:                 BootstrapValidator
markdown:             redcarpet
pygments:             true
highlighter:          pygments
relative_permalinks:  false

destination:          _gh_pages
exclude:              ['node_modules']

redcarpet:
  extensions:         [tables]

ga_code:              UA-44786951-2