name:                 BootstrapValidator
pygments:             false
relative_permalinks:  false

destination:          _gh_pages
exclude:              ['node_modules', '*.less']

# Custom variables
# not defined by Jekyll
current_version:      0.3.2
repository:
  source:             https://github.com/nghuuphuoc/bootstrapvalidator
  docs:               https://github.com/nghuuphuoc/bootstrapvalidator/gh-pages
  docs_edit:          https://github.com/nghuuphuoc/bootstrapvalidator/edit/gh-pages
ga_code:              UA-44786951-2
download:             https://github.com/nghuuphuoc/bootstrapvalidator/archive/v0.3.2.zip